import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import "./globals.css";
import "./theme-config.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.variable}>
        <Theme
          appearance="light"
          accentColor="jade"
          grayColor="mauve"
          radius="large"
        >
          <NavBar />
          <div className="w-[95vw] mx-auto bg-slate-300 h-[1px] my-5" />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
